version: '2'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./server:/code
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - 9200:9200
  kibana:
    image: kibana:latest
    ports:
      - 5601:5601
    links:
      - elasticsearch

